### ISSUE TITLE
Problem with rebuilding index due to Timecourses

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#222]
```
docker-compose run --rm web ./manage.py search_index --rebuild
```
retults in
```
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 134, in handle
    self._rebuild(models, options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 115, in _rebuild
    self._populate(models, options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 92, in _populate
    doc().update(qs)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 231, in update
    self._get_actions(object_list, action), **kwargs
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 191, in bulk
    return bulk(client=self.connection, actions=actions, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('2 document(s) failed to index.', [{'index': {'_index': 'timecourses', '_type': 'timecourse_document', '_id': '78', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'json_parse_exception', 'reason': "Non-standard token 'Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@9351497; line: 1, column: 900]"}}, 'data': {'pk': 78, 'group': {'pk': 70, 'name': 'all'}, 'individual': None, 'interventions': [{'pk': 134, 'name': 'Dcaf'}], 'substance': {'name': 'caffeine'}, 'ex': {'pk': 24}, 'final': True, 'value': None, 'mean': [0.15, 1.07, 3.16, 4.13, 3.95, 3.54, 3.37, 3.07, 2.88, 2.67, 2.01, 1.47, 0.88, 0.51, 0.18, 0.07, 0.0], 'median': None, 'min': None, 'max': None, 'se': [0.0425, 0.1675, 0.3375, 0.1175, 0.085, 0.0925, 0.095, 0.115, 0.105, 0.11, 0.11, 0.0825, 0.085, 0.0625, 0.0225, 0.0225, 0.015], 'sd': [0.17, 0.67, 1.35, 0.47, 0.34, 0.37, 0.38, 0.46, 0.42, 0.44, 0.44, 0.33, 0.34, 0.25, 0.09, 0.09, 0.06], 'cv': [1.13333333333333, 0.626168224299065, 0.427215189873418, 0.113801452784504, 0.0860759493670886, 0.104519774011299, 0.112759643916914, 0.149837133550489, 0.145833333333333, 0.164794007490637, 0.218905472636816, 0.224489795918367, 0.386363636363636, 0.490196078431373, 0.5, 1.28571428571429, inf], 'unit': 'mg/l', 'time_unit': 'h', 'figure': '/media/data/Healy1991_Fig1.png', 'time': [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 6.0, 8.0, 12.0, 16.0, 24.0, 32.0, 48.0], 'tissue': 'plasma', 'pktype': 'concentration', 'auc_end': 32.035}}}, {'index': {'_index': 'timecourses', '_type': 'timecourse_document', '_id': '80', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'json_parse_exception', 'reason': "Non-standard token 'Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1d4c6ff7; line: 1, column: 941]"}}, 'data': {'pk': 80, 'group': {'pk': 70, 'name': 'all'}, 'individual': None, 'interventions': [{'pk': 134, 'name': 'Dcaf'}, {'pk': 135, 'name': 'Dlom'}], 'substance': {'name': 'caffeine'}, 'ex': {'pk': 24}, 'final': True, 'value': None, 'mean': [0.15, 0.82, 2.6, 3.48, 3.81, 3.68, 3.38, 3.09, 2.88, 2.54, 2.01, 1.47, 0.82, 0.47, 0.17, 0.06, 0.0], 'median': None, 'min': None, 'max': None, 'se': [0.0475, 0.0825, 0.2875, 0.19, 0.13, 0.075, 0.0825, 0.1075, 0.0925, 0.125, 0.08, 0.0925, 0.0725, 0.0625, 0.035, 0.0275, 0.0125], 'sd': [0.19, 0.33, 1.15, 0.76, 0.52, 0.3, 0.33, 0.43, 0.37, 0.5, 0.32, 0.37, 0.29, 0.25, 0.14, 0.11, 0.05], 'cv': [1.26666666666667, 0.402439024390244, 0.442307692307692, 0.218390804597701, 0.136482939632546, 0.0815217391304348, 0.0976331360946746, 0.13915857605178, 0.128472222222222, 0.196850393700787, 0.159203980099503, 0.251700680272109, 0.353658536585366, 0.531914893617021, 0.823529411764706, 1.83333333333333, inf], 'unit': 'mg/l', 'time_unit': 'h', 'figure': '/media/data/Healy1991_Fig1.png', 'time': [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 6.0, 8.0, 12.0, 16.0, 24.0, 32.0, 48.0], 'tissue': 'plasma', 'pktype': 'concentration', 'auc_end': 30.8275}}}])

```

**Comment by matthiaskoenig** [comment]
This works now.
