### ISSUE TITLE
rebuild_index results in errors

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#279]
When I run `./rebuild_index.sh` I get the following errors
```
/code/pkdb_app/analysis/pharmacokinetic.py:368: RuntimeWarning: divide by zero encountered in log
  y = np.log(c[max_index:])
/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py:2320: RuntimeWarning: invalid value encountered in subtract
  X -= avg[:, None]
/code/pkdb_app/analysis/pharmacokinetic.py:368: RuntimeWarning: invalid value encountered in log
  y = np.log(c[max_index:])
POST http://elasticsearch:9200/_bulk [status:200 request:0.104s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/fields.py", line 52, in get_value_from_instance
    instance = instance[attr]
TypeError: 'Timecourse' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/fields.py", line 58, in get_value_from_instance
    instance = getattr(instance, attr)
  File "/code/pkdb_app/interventions/models.py", line 520, in interventions
    return self.raw._interventions
AttributeError: 'NoneType' object has no attribute '_interventions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/fields.py", line 63, in get_value_from_instance
    instance = instance[int(attr)]
ValueError: invalid literal for int() with base 10: 'interventions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 134, in handle
    self._rebuild(models, options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 115, in _rebuild
    self._populate(models, options)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 92, in _populate
    doc().update(qs)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 231, in update
    self._get_actions(object_list, action), **kwargs
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 191, in bulk
    return bulk(client=self.connection, actions=actions, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 180, in streaming_bulk
    client.transport.serializer):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 58, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 214, in _get_actions
    yield self._prepare_action(object_instance, action)
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 200, in _prepare_action
    self.prepare(object_instance) if action != 'delete' else None
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py", line 167, in prepare
    instance, self._related_instance_to_ignore
  File "/code/pkdb_app/documents.py", line 79, in get_value_from_instance
    instance, field_value_to_ignore
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/fields.py", line 70, in get_value_from_instance
    "{!r}".format(attr, instance)
django_elasticsearch_dsl.exceptions.VariableLookupError: Failed lookup for key [interventions] in <Timecourse: Timecourse object (761)>
```

**Comment by janekg89** [comment]
should be fixed now
