### ISSUE TITLE
Upload study without PDF (caffeine/IKP243)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#351]
Some studies don't have PDFs attached. Example given `caffeine/IKP243`. 
This failed with
```
b'{"sid":["This field may not be null."],"title":["This field is required."],"date":["This field is required."]}'
Traceback (most recent call last):
  File "/home/mkoenig/envs/pkdb_data/bin/watch_study", line 11, in <module>
    load_entry_point('pkdb-data', 'console_scripts', 'watch_study')()
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 95, in main
    args.func(args)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 71, in start_observer
    event_handler = StudyHandler(path=path, url_base = url_base)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 41, in __init__
    self._changed()
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 58, in _changed
    auth_headers=self.auth_headers)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/upload_studies.py", line 402, in upload_study_from_dir
    auth_headers=auth_headers, client=client)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/upload_studies.py", line 179, in upload_reference_json
    with open(json_reference["pdf"], "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mkoenig/git/pkdb_data/studies/caffeine/IKP243/IKP243.pdf'
```

**Comment by janekg89** [comment]
should work with the latest commit
