### ISSUE TITLE
isdigit error when uploadign study reference

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#361]
E.g. caffeine/Gunes2009
```
INFO --------------------------------------------------------------------------------
INFO Watching [Gunes2009]
INFO 	/home/mkoenig/git/pkdb_data/studies/caffeine/Gunes2009
INFO --------------------------------------------------------------------------------
INFO {'reference_path': '/home/mkoenig/git/pkdb_data/studies/caffeine/Gunes2009', 'name': 'Gunes2009', 'pmid': 19450128}
Traceback (most recent call last):
  File "/home/mkoenig/envs/pkdb_data/bin/watch_study", line 11, in <module>
    load_entry_point('pkdb-data', 'console_scripts', 'watch_study')()
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 94, in main
    args.func(args)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 71, in start_observer
    event_handler = StudyHandler(path=path, url_base=url_base)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 41, in __init__
    self._changed()
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/watch_study.py", line 58, in _changed
    auth_headers=self.auth_headers)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/upload_studies.py", line 417, in upload_study_from_dir
    create_reference(ref)
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/create_reference_json.py", line 30, in run
    save_json(add_doi(create_json(xml_to_data(load_from_biopython(ref_dict)))))
  File "/home/mkoenig/git/pkdb_data/pkdb_data/management/create_reference_json.py", line 41, in load_from_biopython
    if str.isdigit(d["pmid"]):
TypeError: descriptor 'isdigit' requires a 'str' object but received a 'int'
```

**Comment by janekg89** [comment]
solved with commit of pkdb_data
