### ISSUE TITLE
bug after docker-interactive. cannot develop locally.

### ISSUE THREAD

**Issue by janekg89** [matthiaskoenig/pkdb#393]
```
backend_1        | INFO Watching for file changes with StatReloader
backend_1        | Performing system checks...
backend_1        | 
backend_1        | Exception in thread django-main-thread:
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
backend_1        |     return self._engines[alias]
backend_1        | KeyError: 'django'
backend_1        | 
backend_1        | During handling of the above exception, another exception occurred:
backend_1        | 
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
backend_1        |     self.run()
backend_1        |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
backend_1        |     self._target(*self._args, **self._kwargs)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
backend_1        |     fn(*args, **kwargs)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
backend_1        |     self.check(display_num_errors=True)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
backend_1        |     include_deployment_checks=include_deployment_checks,
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
backend_1        |     return checks.run_checks(**kwargs)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
backend_1        |     new_errors = check(app_configs=app_configs)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/checks.py", line 79, in check_dependencies
backend_1        |     for engine in engines.all():
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
backend_1        |     return [self[alias] for alias in self]
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
backend_1        |     return [self[alias] for alias in self]
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
backend_1        |     engine = engine_cls(params)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
backend_1        |     options['libraries'] = self.get_templatetag_libraries(libraries)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
backend_1        |     libraries = get_installed_libraries()
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
backend_1        |     for name in get_package_libraries(pkg):
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
backend_1        |     module = import_module(entry[1])
backend_1        |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend_1        |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1        |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
backend_1        |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
backend_1        |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
backend_1        |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 15, in <module>
backend_1        |     from rest_framework.renderers import HTMLFormRenderer
backend_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/renderers.py", line 20, in <module>
backend_1        |     from django.test.client import encode_multipart
backend_1        |   File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 23, in <module>
backend_1        |     from django.test import signals
backend_1        |   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 149, in __enter__
backend_1        |   File "<frozen importlib._bootstrap>", line 94, in acquire
backend_1        | _frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('django.test.signals') at 140604126931432
backend_1        | 
```

**Comment by janekg89** [comment]
I think it is due to 37fb6aca096ff52f79711ce8d4653b0f8199354b sercurity realted updates

**Comment by matthiaskoenig** [comment]
I cannot reproduce this. I did the deployment without any issues after the changes and also locally everything is working.
